name: Build and Run C++ Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx build --file Dockerfile --tag marcom3622/myapp:1.0.0 .

      - name: Run C++ application
        run: |
          docker run marcom3622/myapp:1.0.0
